### ISSUE TITLE
OMXplayer process dies at completion of video?

### ISSUE THREAD

**Issue by Landfishy** [willprice/python-omxplayer-wrapper#141]
Hi there guys, I don't know if this is a bug or not. If I let a video run to completion, I cannot call the instantiated OMXplayer to run a new video. I get an error:

raise OMXPlayerDeadError('Process is no longer alive, cant\'t run command') 
omxplayer.player.OMXPlayerDeadError: Process is no longer alive, can't run command. 

I was trying to monitor the status of the video player so that I could know when other content should be loaded, and was filtering out exceptions when I discovered the process was actually dying as it returned exceptions. When when I tried to send it a command after that, obviously things blew up. Heres some pseudo code for the use case...is there something I am doing wrong or is this actually an issue?

```python
from omxplayer import OMXPlayer


class VideoPlayer(): 
    def __init__ (self):
        self.omx = None

    def Playloop(self, fullpath, startPosition):
        self.omx = OMXPlayer(fullpath, args=['-o', 'hdmi', '--no-osd', '--alpha', '80'])


def runProgram():
    myBGPlayer = VideoPlayer()
    myBGplayer.PlayLoop('/etc/media/Ball.mp4')

    while(1):
        try:
            #  Check for single player status once the player has been instantiated
            if myBGPlayer.omx:
                status = myPlayer.omx.playback_status()
            else:
                status = 'stopped'
        except:
            print("An exception occurred 001")

```

**Comment by willprice** [comment]
You'll need to [`load`](https://python-omxplayer-wrapper.readthedocs.io/en/latest/omxplayer/#omxplayer.player.OMXPlayer.load) a new video once the first one completes. 
I think the changes from https://github.com/willprice/python-omxplayer-wrapper/pull/116 will allow you to implement what you're after.

Basically you'll want to register a callback on `exitEvent` to do something when the video finishes.
