### ISSUE TITLE
Provide a callback for when the process exits

### ISSUE THREAD

**Issue by willprice** [willprice/python-omxplayer-wrapper#15]

**Comment by MydKnight135** [comment]
I need something like this myself to allow for running another video, this time on loop, after the first one finishes.

**Comment by willprice** [comment]
@MydKnight135 So you would be opening a new video/new instance of OMXPlayer? 

This clashes with #18, if I implement a daemon mode then there is no need for a callback for process exit, but that would be quite complicated. I may add this as an intermediary solution until I implement a daemon mode, if that is what should be done ;)

**Comment by willprice** [comment]
Decided against daemon mode, so it would make sense to implement this.

**Comment by willprice** [comment]
This should be quite easy by monitoring when the process exits.

Alternatively we could run with `--loop` if the DBus `seeked` signal is generated which would allow us to pause.

**Comment by willprice** [comment]
We spin up a monitor when starting the process, perhaps we can inject an exit callback there that is called once the monitor detects the process exit.

**Comment by willprice** [comment]
Present in develop branch as of https://github.com/willprice/python-omxplayer-wrapper/commit/75dbfa2d199256627ebede9ff470b400e51ca003
