### ISSUE TITLE
Implement SetLayer method

### ISSUE THREAD

**Issue by JE-Random-Tech** [willprice/python-omxplayer-wrapper#189]
# Feature Request
## Description

For seamless video switching it would be ideal to be able to change the Layer of the Video while it is playing.

## Example use case
Setting the alpha channel to 255 or hide the video does not work as it always flickers therefor it is necessary to create a seamless video transition.

**Comment by JE-Random-Tech** [comment]
I have already a working solution and would like to contribute it.

**Comment by willprice** [comment]
Hi @JE-Random-Tech,

That sounds great. Just click the 'fork' button on the top right of this page to create your own copy of the repo. Once you've done that you can push your changes to the fork and open a pull request. The method should be in snake case for consistency with the rest of the API, i.e. `set_layer`.

Thanks :)

**Comment by willprice** [comment]
Added in #191
