### ISSUE TITLE
Missing docs on how to run tests

### ISSUE THREAD

**Issue by matthijskooijman** [willprice/python-omxplayer-wrapper#200]
I was trying to be a good citizen and run the tests for a PR I'm about to create, but I could not find any docs about how to approach this exactly. I found `make test` in the Makefile, but that does not install dependencies. I found that `pip3 install -e .[test]` works to install the dependencies, and together it seems to pass the testsuite, but maybe it would be good to include this in official documentation somewhere?

**Comment by willprice** [comment]
Addressed in a9875e3
