### ISSUE TITLE
hide the status and time information at movie start

### ISSUE THREAD

**Issue by electricgraphy** [willprice/python-omxplayer-wrapper#28]
Hi Will

thank you for your wonderful source.
is there any method to hide the status and time information on screen when the movie starts?

Jin

**Comment by willprice** [comment]
You can pass command line arguments in the `OMXPlayer` constructor, perhaps `--no-osd` is what you're looking for?

**Comment by electricgraphy** [comment]
thank you for the quick reply.

sorry I'm just newbie on python and linux. ;)  
I tried to make some video-installation between 2 raspberry pi that must communicate each other.
so the platform must be python.

the part of omxplayer in my code is so simple.
just like this:
player = OMXPlayer('path/to/file.mp4')
player.play()
sleep(player.duration())
player.quit()

I wonder if you could explain in detail how I control or use the arguments in the OMXPlayer.
is it possible with this code?  

thank you very much
Jin

**Comment by willprice** [comment]
initialise with `OMXPlayer('path.mp4', args=['--no-osd'])`

**Comment by electricgraphy** [comment]
Thank you so much! It work. :)
