### ISSUE TITLE
Stop information overlay from showing.

### ISSUE THREAD

**Issue by NonaSuomy** [willprice/python-omxplayer-wrapper#29]
How do you stop player from overlaying any information on the screen (Playing, Time, etc) just want video nothing else

**Comment by willprice** [comment]
Please look through previously closed issues as this has already come up
and been solved

**Comment by NonaSuomy** [comment]
I found this initialise with OMXPlayer('path.mp4', args=['--no-osd']) how do I add multiples?

initialise with OMXPlayer('path.mp4', args=['--no-osd --no-keys -b'])   ?

This gave me an error saying: unrecognised options '--no-osd --no-keys -b'

**Comment by NonaSuomy** [comment]
I tried OMXPlayer('path.mp4', args=['--no-osd'], args=['--no-keys'], args=['-b'])
No luck, SyntaxError: keyword argument repeated.

Just to note I've tested the options directly with the player and they work fine ie: omxplayer --no-osd --no-keys -b path.mp4 etc

**Comment by NonaSuomy** [comment]
This may have worked for future people with this issue: OMXPlayer('path.mp4', args=['--no-osd', '--no-keys', '-b'])
