### ISSUE TITLE
Is there a way to Overlay custom text on to OMXPlayer?

### ISSUE THREAD

**Issue by NonaSuomy** [willprice/python-omxplayer-wrapper#31]
Say I have A count down timer running when the timer hits zero it quits the video.

I want to overlay that timer text so the user can see it ticking down.

I tried to use pygame but it only works if the video has black bars at the top/bottom and when you put the timer close to the video it starts to get tucked under it instead of on top like the subtitles etc.

Also if this was plausible and I have --no-osd set, would that make it so it would not show my custom timer?

Thank you for your time.

**Comment by willprice** [comment]
Sorry, I have no idea. Perhaps you can look into the layer option on OMXPlayer, this is more of a question for them than this project; even better would be the RPi forums. Good luck.
