### ISSUE TITLE
Provide callbacks for actions like play, pause, stop, set_position, seek

### ISSUE THREAD

**Issue by markkorput** [willprice/python-omxplayer-wrapper#49]
Kinda like #15, but easier to implement; the callbacks can simply be triggered by the corresponding methods in the OMXPlayer class and don't need to originate from the omxplayer process.

(I personally need this for the omxsync package at I'm writing at https://github.com/markkorput/pyOmxSync, which is inspired by the omxplayer-sync repo, but uses OMXPlayer as an interface to be more easily used in python projects).

**Comment by willprice** [comment]
Nice! Thanks for the contribution.

**Comment by willprice** [comment]
Tests are fixed so you're good to work off `develop` :)

**Comment by willprice** [comment]
Refactored some of Marks code and merged in #56
