### ISSUE TITLE
Make pausing at instantiation optional

### ISSUE THREAD

**Issue by markkorput** [willprice/python-omxplayer-wrapper#51]
Currently the OMXPlayer's constructor class immediately pauses playback after spawning the omxplayer process. This can be nice, but often playback should start directly anyway.

##### User Story
When spawning playback on multiple raspberries at the same time (triggered for example via sockets, or an OSC message); playback is reasonably synchronised (especially when running the same raspbian system on the same version of the RaspberryPI). Running one instance on an older version of the raspi your get a (be it hardly noticeable) delay on the slower raspi, simply because it takes a little bit longer to load the first frames into memory. Having an additional and unnecessary pause/play action in between probably won't help.

##### Solution direction
simply add a 'pause=True' argument to the constructor

**Comment by willprice** [comment]
Good idea, I'd welcome a pull request ;)
