### ISSUE TITLE
Running two videos consecutively

### ISSUE THREAD

**Issue by willprice** [willprice/python-omxplayer-wrapper#7]
Trying to run two videos consecutively doesn't work, the second video does not play.

**Comment by jthuraisamy** [comment]
Is it that the second video does not play at all, or it plays simultaneously with the first video?

**Comment by willprice** [comment]
This is now fixed and can be verified by running `smoke-tests/test2.py` which runs two consecutive videos

**Comment by JonnyAlpha** [comment]
Will, just tried to run the smoke-tests/test2.py, python hung saying that OMXplayer had no attribute exit, so I changed the code to vid1.quit() and vid2.quit(). Was this a typo?

**Comment by JonnyAlpha** [comment]
Just played with the code and successfully played two videos (one immediately after the other) with no gaps, a seamless transition which is exactly what I was looking for earlier this year, brilliant, many thanks Will, I can now continue with my project :-)

**Comment by willprice** [comment]
Thanks for the correction Jonny, I'll push the edits later today.
:+1:

**Comment by alexis85120** [comment]
Hi Will, I don't understand. How do you run smoke-tests/test2.py ? And what will it help to play 2 videos ?
