### ISSUE TITLE
Consider switching to a permissive licence

### ISSUE THREAD

**Issue by jthuraisamy** [willprice/python-omxplayer-wrapper#8]
I just noticed that this project is licensed under the GPL, which may significantly restrict its adoption and use.

This is because any and all other projects which depend on this library would be forced to switch their own licences to GPL and release all of their source code even if its relation to this library is minimal. Were it to be licenced under a MIT-style licence, it would be possible to avoid that.

That said, the decision is yours, of course.

**Comment by willprice** [comment]
How about LGPL? I'd rather not go with MIT as it's so permissive and someone could take the library modify it, and not contribute back improvements.

**Comment by jthuraisamy** [comment]
I agree.  LGPL would work. :+1:

**Comment by willprice** [comment]
Thanks for the tip, I wasn't aware GPL was /that/ restricitve. I'll add a commit

**Comment by willprice** [comment]
Fixed in ae7baf3ec1ae0deac93c378c151eb1c3f37f9bf2
