### ISSUE TITLE
Wrapper not working  open CV

### ISSUE THREAD

**Issue by GitTestProject360** [willprice/python-omxplayer-wrapper#87]
# omxplayer wrapper not working in cv
## Description
omxplayer wrapper not working in cv (please see screenshot below)
![omxplayerwrapper](https://user-images.githubusercontent.com/22218060/27715462-ecd03a2a-5cfc-11e7-88ff-8a3ba065ce0b.jpg)

A short description of the problem
sample code stream rtsp stream from IP camera. outside cv  working fine (see above screenshot).if i change to CV .code not working. Omxplayer  wrapper install on OpenCV version 3.2.0

![omxplayerwrapper1](https://user-images.githubusercontent.com/22218060/27715514-6b2f8c90-5cfd-11e7-87f7-3b54d1958238.jpg)
## Environment details
![omxplayerwrapper2](https://user-images.githubusercontent.com/22218060/27715769-11f04208-5cff-11e7-9b21-6d9a6b52cfbd.jpg)

 ## working in python 3 but not in cv pytho3. i need to run wrapper in side Opencv (version 3.2.0) so i can added text in rtsp stream before play in omxplayer. thanks 

Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie
```

| Software | Version |
|----------|---------|
| `python-omxplayer-wrapper` |insatlled from this link https://github.com/willprice/python-omxplayer-wrapper/tree/python_2_3_support|
| `python-dbus` (`dpkg -s python-dbus`) |  `1.2.0` |
| `python` (`python --version`) | `3` |
| `omxplayer` (`omxplayer --version`) | `6c90c75` |


Thanks

**Comment by willprice** [comment]
Looks like your virtualenvironment (workon cv) doesn't have omxplayer installed. After running workon do a `pip install omxplayer-wrapper`
