### ISSUE TITLE
Default BusFinder path may never exist

### ISSUE THREAD

**Issue by jthuraisamy** [willprice/python-omxplayer-wrapper#9]
The default path of `/tmp/omxplayerdbus.root` will only exist if omxplayer is run by root.

I'm having issues where omxplayer is not able to detect the user when the wrapper is launched from an `init.d` script. When this happens the file that is created ends up being named `/tmp/omxplayerplus.`.

So I'm modifying the `wait_for_file` method again such that under the condition where `self.path` is not explicitly defined on BusFinder initialisation, it would pick the most recent `/tmp/omxplayerplus.*` file to be assigned to `self.path`.

**Comment by willprice** [comment]
Fixed in current develop branch (integerated @jthuraisamy code)
