### ISSUE TITLE
"ImportError: No Module named 'dbus'

### ISSUE THREAD

**Issue by chelseamw13** [willprice/python-omxplayer-wrapper#92]
# Issue Report
## Description
I am able to run the wrapper using python2, however when I run it with python3 (after downloading your python_2_3 support) I get the above error. I have re installed dbus quite a few times but I believe the problem is that it's not installing properly. Do you have a recommended way to install dbus?

## Example
python3 test.py
```
Import Error: No module named 'dbus'

have tried the following ways of installing  dbus

sudo apt-get install python-dbus
...
"python-dbus is already the newest version."

sudo apt-get install python3-dbus
...
"python3-dbus is already the newest version."


sudo pip3 install dbus-python

...
Error: Command "/usr/bin/python -u -c "import setup tools, tokenize;__file__='/tmp/pip-build-eabW81/dbus-python/setup.py.....
```
## Environment details
* OS (`lsb_release -a`):
```
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie
```

| Software | Version |
|----------|---------|
| `python-omxplayer-wrapper` | `0.1.0` |
| `python-dbus` (`dpkg -s python-dbus`) |  `1.2.0-2` |
| `python` (`python --version`) | `2.7.9` |
| `omxplayer` (`omxplayer --version`) | `dfeaBc9` |

-------

**Comment by willprice** [comment]
Try off master, I thought I merged py3 support in.

**Comment by chelseamw13** [comment]
I tried it of master as well but no luck!

**Comment by chelseamw13** [comment]
Thank you anyways! I fixed it by creating a virtualenv -- was having problems with python3.4 vs python3.5
